#playbook to run docker role which builds image and deploy the containers
---
- name: set up docker, build images and deploy application
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
  - docker

