---
- name: Ensure that docker is installed
  apt:
    name: docker
    state: latest

- name: Ensure docker is running
  systemd:
    state: started
    name: docker

- name: build go app image from dockerfile
  docker_image: 
    path: /home/ubuntu/ansible
    name: goapp
    tag: latest

- name: build nginx app image from dockerfile
  docker_image:
    path: /home/ubuntu/ansible/nginx
    name: nginx
    tag: latest

- name: launch go container
  docker_container:
    name: goapp
    image: goapp:latest
    network_mode: host 
    restart_policy: always

- name: Launch nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    network_mode: host
    restart_policy: always
